######################################################################
# Automatically generated by qmake (3.0) Thu Aug 17 18:56:09 2017
######################################################################

TEMPLATE = app
TARGET = qthw
INCLUDEPATH += .

QT += core gui widgets

# Input
SOURCES += qthw.cpp
